modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/P3ridot/MangoOres/issues"
[[mods]] #mandatory
modId="mangoores"
version="${file.jarVersion}"
displayName="MangoOres"
displayURL="https://github.com/P3ridot/MangoOres" #optional
logoFile="logo.png"
credits="Thanks for: piotreee, Arek and WBGroup <3"
authors="Peridot and Czerwonek"
description='''Mod  which add new very cool items, blocks, mobs and more!'''
